#!/usr/bin/env npx tsx
/**
 * All-DeepSeek overnight multi-agent orchestrator (generic, role-based skeleton).
 *
 * Generated by the `deepseek-overnight` skill. An ARBITRARY set of agents runs
 * on DeepSeek via the @anthropic-ai/claude-code SDK, organized by ROLE:
 *
 *   - planner   : runs BEFORE the dev wave. Reads the previous stage's outcome
 *                 + BLOCKED.md and produces/adjusts this stage's guidance. Also
 *                 triages blocked items (replan an alternative, or mark for the
 *                 morning) — the overnight stand-in for human escalation.
 *   - worker    : builds the code. A "researcher" is just a worker with no gates.
 *   - reviewer  : advisory critic. Add several for multi-critic review (e.g. one
 *                 security, one API-design); their change requests are merged.
 *
 * Each stage runs:  PLAN → DEV (waves) → GATE → REVIEW (N critics) → FIX → loop.
 * Reliability comes from the deterministic GATE MACHINE (not the reviewers),
 * frozen spec tests, a DeepSeek-only guard, conditional commits, readable logs.
 *
 * FILL every section marked `CONFIG — FILL PER PROJECT`; leave the machinery.
 *
 * Launch:
 *   export ANTHROPIC_BASE_URL="https://api.deepseek.com/anthropic"
 *   export ANTHROPIC_AUTH_TOKEN="$DEEPSEEK_API_KEY"
 *   npx tsx orchestrate.ts --stage 0
 *   npx tsx orchestrate.ts --continuous
 *   npx tsx orchestrate.ts --stage 3 --skip a2,researcher
 */

import { query } from '@anthropic-ai/claude-code';
import { readFileSync, writeFileSync, existsSync, createWriteStream, mkdirSync, type WriteStream } from 'fs';
import { resolve } from 'path';
import { execSync } from 'child_process';
import { evalDir } from './scripts/visual-eval';

const ROOT = import.meta.dirname;
const DEFAULT_MAX_ROUNDS = 5;
const BLOCKED_FILE = resolve(ROOT, 'BLOCKED.md');
// Wall-clock backstop per agent — catches a GENUINELY hung agent overnight without
// ever cutting off a productive build. We do NOT cap turn-count: a high turn-count
// round can be productive (a real run built an entire page in 228 turns / ~15 min).
// Budgets are deliberately generous (≈2× the longest real run) so only true hangs trip.
const WORKER_WALL_MS = Number(process.env.WORKER_WALL_MS ?? 30 * 60_000); // workers: 30 min
const REASON_WALL_MS = Number(process.env.REASON_WALL_MS ?? 5 * 60_000);  // tool-less reasoning: 5 min

// ======================= CONFIG — FILL PER PROJECT =======================

const ORCH_MODEL = process.env.ORCH_MODEL ?? 'deepseek-v4-pro';            // workers (code gen)
const ORCH_MODEL_CHEAP = process.env.ORCH_MODEL_CHEAP ?? 'deepseek-v4-flash'; // cheap roles
// Reasoning model for the reasoning-heavy roles (planner + reviewers). Those roles
// run TOOL-LESS (text in → text out), so a pure reasoning model is the right fit —
// R1 can't reliably tool-call anyway, which is exactly why those slots are tool-less.
// Default is DeepSeek-R1. NOTE: the `deepseek-reasoner` alias retires 2026-07-24 —
// swap to its successor model id after that date.
const ORCH_MODEL_REASON = process.env.ORCH_MODEL_REASON ?? 'deepseek-reasoner';

type Role = 'planner' | 'worker' | 'reviewer';
interface GateCmd { label: string; cmd: string; cwd: string; presentIf: string }
interface AgentDef {
  id: string;
  label: string;
  systemFile: string;
  role: Role;
  reviewHeading?: string;
  perspective?: string;
  model?: string;
  gates?: GateCmd[];
}

const CORE = 'packages/core', CLI = 'packages/cli', CONTRACTS = 'contracts', WEB = 'apps/web';
// LOCAL ONLY — agents must NEVER deploy to or test against testnet/mainnet. Contract
// correctness is proven with cargo test (soroban-sdk in-memory env, no network).
const AGENTS: Record<string, AgentDef> = {
  planner: {
    id: 'planner', label: 'P Planner', systemFile: 'planner.md', role: 'planner', model: ORCH_MODEL_REASON,
  },
  a1: {
    id: 'a1', label: 'A1 Contract', systemFile: 'a1.md', role: 'worker', reviewHeading: 'A1',
    gates: [
      { label: 'contract build', cmd: 'stellar contract build', cwd: CONTRACTS, presentIf: `${CONTRACTS}/Cargo.toml` },
      { label: 'cargo test', cmd: 'cargo test --quiet', cwd: CONTRACTS, presentIf: `${CONTRACTS}/Cargo.toml` },
    ],
  },
  a2: {
    id: 'a2', label: 'A2 SDK', systemFile: 'a2.md', role: 'worker', reviewHeading: 'A2',
    gates: [
      { label: 'core tsc', cmd: 'npx tsc --noEmit', cwd: CORE, presentIf: `${CORE}/tsconfig.json` },
      { label: 'core tests', cmd: 'npx vitest run --passWithNoTests', cwd: CORE, presentIf: `${CORE}/package.json` },
    ],
  },
  a3: {
    id: 'a3', label: 'A3 CLI', systemFile: 'a3.md', role: 'worker', reviewHeading: 'A3',
    gates: [
      { label: 'cli tsc', cmd: 'npx tsc --noEmit', cwd: CLI, presentIf: `${CLI}/tsconfig.json` },
      { label: 'cli tests', cmd: 'npx vitest run --passWithNoTests', cwd: CLI, presentIf: `${CLI}/package.json` },
    ],
  },
  a5: {
    id: 'a5', label: 'A5 Designer', systemFile: 'a5.md', role: 'worker', reviewHeading: 'A5',
    // Design-system ENGINEER: turns the authored art-direction brief (apps/web/DESIGN.md +
    // a5.md) into code — design tokens, the reusable themed component kit, brand SVG. It
    // does NOT judge taste (DeepSeek has no vision); the human art-directs, qwen is the eye.
    gates: [
      { label: 'web build', cmd: 'npm run build', cwd: WEB, presentIf: `${WEB}/package.json` },
    ],
  },
  a4: {
    id: 'a4', label: 'A4 Web', systemFile: 'a4.md', role: 'worker', reviewHeading: 'A4',
    gates: [
      // `npm run build` = next build (tsc + bundle). Playwright runs button/interaction
      // tests AND captures screenshots (apps/web/screenshots) for the visual review.
      { label: 'web build', cmd: 'npm run build', cwd: WEB, presentIf: `${WEB}/package.json` },
      { label: 'web e2e + shots', cmd: 'npx playwright test', cwd: WEB, presentIf: `${WEB}/playwright.config.ts` },
    ],
  },
  review_correctness: {
    id: 'review_correctness', label: 'Reviewer (correctness)', systemFile: 'reviewer-correctness.md', role: 'reviewer',
    model: ORCH_MODEL_REASON,
    perspective: 'escrow money-safety (funds release ONLY on confirmed delivery and refund ONLY on the agreed conditions; no double-release, no fund-lock, no unauthorized release), state-machine soundness, reputation integrity, and matching determinism',
  },
  review_design: {
    id: 'review_design', label: 'Reviewer (design)', systemFile: 'reviewer-design.md', role: 'reviewer',
    model: ORCH_MODEL_REASON,
    perspective: 'API design, naming, integration between the Soroban contract / @stellarcarry/core SDK / CLI, and for the web app (apps/web): reuse of the UI primitives, UX clarity, empty/loading/error states, and accessibility',
  },
};

const RUN_ORDER: string[] = ['planner', 'a1', 'a2', 'a3', 'a5', 'a4'];
const BUILD_BETWEEN_WAVES: string | null = null; // TS consumed from src via tsx/vitest; the contract has its own build gate
const FROZEN_TESTS: string[] = ['packages/core/test/matching.test.ts'];

interface StagePlan { title: string; waves: string[][]; tasks: Record<string, string> }
const STAGE_PLANS: Record<number, StagePlan> = {
  // ── Stage 0: matching engine + contract & CLI skeletons ───────────────────
  // packages/core and packages/cli are pre-scaffolded (stubs + FROZEN test) and
  // committed; a1 creates the contracts/ workspace. Independent dirs → 1 wave.
  0: {
    title: 'Matching engine + contract & CLI skeletons',
    waves: [['a1', 'a2', 'a3']],
    tasks: {
      a2: `packages/core (@stellarcarry/core) is already scaffolded (types, stubs, index, and a FROZEN test). Your job:
1. Confirm src/types.ts matches what the FROZEN test packages/core/test/matching.test.ts imports.
2. IMPLEMENT matchTravelers in src/matching.ts so the frozen test passes:
   - FILTER to travelers that can do the job: traveler.fromCountry === request.fromCountry AND traveler.toCountry === request.toCountry AND traveler.travelDay <= request.deadlineDay AND traveler.capacityG >= request.itemWeightG.
   - SCORE each survivor by score = reputation (integer 0..100).
   - SORT by score descending; tie-break by travelDay ascending, then by id ascending.
   - Return [{ travelerId, score }]. Pure + deterministic.
3. Leave EscrowClient (src/client.ts) as a stub for now.
Do NOT modify the frozen test. core tsc + vitest must pass.`,
      a1: `Create the Soroban escrow contract skeleton in contracts/ (Rust). LOCAL ONLY — never deploy or hit any network.
1. contracts/Cargo.toml: a Rust workspace with member "escrow".
2. contracts/escrow/Cargo.toml: a cdylib crate depending on soroban-sdk, with the "testutils" feature enabled as a dev-dependency for tests.
3. contracts/escrow/src/lib.rs: #![no_std]; an empty #[contract] struct EscrowContract with a #[contractimpl] block (no methods yet), and a #[contracttype] enum EscrowState { Created, Funded, Delivered, Released, Refunded }.
'stellar contract build' and 'cargo test' must both succeed (an empty contract builds and has zero tests).`,
      a3: `packages/cli (@stellarcarry/cli) is already scaffolded. Flesh out the commander entry in src/index.ts with STUB commands post-request and add-traveler that write to the JSON store (src/store.ts). Import types from @stellarcarry/core; never reimplement core logic. tsc must be clean.`,
    },
  },
  // ── Stage 1: escrow contract core + SDK client ────────────────────────────
  1: {
    title: 'Escrow contract core + SDK client',
    waves: [['a1', 'a2']],
    tasks: {
      a1: `Implement the escrow state machine in contracts/escrow/src/lib.rs. LOCAL ONLY — prove correctness with cargo test using the soroban-sdk in-memory test env (NO network, NO deploy).
Methods on EscrowContract (use soroban_sdk types: Env, Address, ids, i128 amounts; persist escrows in storage):
- create_escrow(env, buyer: Address, traveler: Address, amount: i128) -> escrow id; state = Created. buyer must require_auth().
- fund(env, id): buyer transfers 'amount' of the payment token into the contract; state Created -> Funded. Only the buyer; only from Created.
- confirm_delivery(env, id): buyer confirms receipt; state Funded -> Delivered. Only the buyer; only from Funded.
- release(env, id): pay the escrowed amount to the traveler; state Delivered -> Released. Allowed only from Delivered.
- refund(env, id): return the escrowed amount to the buyer; allowed only from Funded (not after Delivered/Released). state -> Refunded.
INVARIANTS (write cargo tests asserting each): funds release ONLY after confirm_delivery; refund is impossible after release and vice-versa (no double-spend); every method panics from the wrong state; only authorized parties can act.`,
      a2: `Implement EscrowClient in packages/core/src/client.ts — a thin wrapper that BUILDS Stellar/Soroban transactions to invoke the escrow contract (createEscrow/fund/confirmDelivery/release/refund). Use @stellar/stellar-sdk. The default network config is LOCAL ONLY (the Docker quickstart RPC at http://localhost:8000); NEVER default to or accept testnet/mainnet. Unit-test the transaction BUILDING (operation structure, contract-id wiring) with vitest — do NOT require a live network in tests. Do NOT modify the frozen matching test.`,
    },
  },
  // ── Stage 2: reputation + CLI lifecycle ───────────────────────────────────
  2: {
    title: 'Reputation + CLI lifecycle',
    waves: [['a1'], ['a3']],
    tasks: {
      a1: `Extend contracts/escrow: an on-chain reputation map (Address -> i128) incremented on release(); a refund path guarded by an agreed deadline ledger timestamp (refund allowed only after the deadline if not yet Delivered). Add cargo tests for reputation-increment-on-release and the deadline-guarded refund. Keep ALL Stage 1 invariants. LOCAL ONLY.`,
      a3: `Build the full CLI in packages/cli, delegating to @stellarcarry/core (matchTravelers + EscrowClient) and the store:
- post-request, add-traveler (finalize), match <requestId> (print ranked travelers).
- create-escrow <requestId> <travelerId>, fund <escrowId>, confirm-delivery <escrowId>, release <escrowId>, refund <escrowId>.
tsc clean; add a smoke test for the store round-trip and a match test on a fixed fixture. LOCAL network only — never accept a testnet/mainnet target.`,
    },
  },
  // ── Stage 3: hardening ────────────────────────────────────────────────────
  3: {
    title: 'Hardening + edge cases',
    waves: [['a1', 'a2', 'a3']],
    tasks: {
      a1: `Harden contracts/escrow with cargo tests for every failure mode: acting from the wrong state panics, unauthorized callers are rejected, no double-release or double-refund, refund blocked after Delivered/Released. Do NOT weaken existing tests.`,
      a2: `Harden @stellarcarry/core: typed errors in EscrowClient for bad input, defensive validation in matchTravelers (empty travelers -> [], guard malformed request fields), and JSDoc on all public functions. Do NOT modify the frozen test.`,
      a3: `Harden @stellarcarry/cli: actionable error messages (unknown id, no data yet, invalid amount), input validation (positive integer amounts, known ids), a --help summary, and a hard guard that the network target can only be LOCAL (reject any testnet/mainnet value).`,
    },
  },
  // Stage 4: post-request + travelers (premium)
  4: {
    title: 'UI: post-request + travelers (premium)',
    waves: [['a4']],
    tasks: {
      a4: `apps/web is a Next.js 16 app. The landing app/page.tsx is the premium gold standard (dark theme, Stellar yellow #FDDA24, real Aceternity/Magic UI components in components/ui/, logo in components/brand/logo.tsx, seed in lib/seed.ts). MATCH ITS QUALITY -- compose those components; do NOT hand-roll plain CSS. Build two routes:
1. app/post/page.tsx: a premium "post a request" form (from/to country, item weight g, reward in XLM, deadline day). Validate positive integers and non-empty countries with inline errors; show a success state on submit. Glowing yellow submit button.
2. app/travelers/page.tsx: browse lib/seed seedTravelers as premium cards (route, travel day, capacity, reputation), an "add traveler" form, and an empty state.
Wire both into the header nav. For EACH page add a Playwright screenshot (await page.waitForTimeout(1500) then screenshot to screenshots/<name>.png) and a button-interaction test in apps/web/e2e/.
Gates: npm run build + npx playwright test.`,
    },
  },
  // Stage 5: matching + wallet (premium)
  5: {
    title: 'UI: matching results + wallet connect (premium)',
    waves: [['a4']],
    tasks: {
      a4: `Add app/match/page.tsx: pick a request from lib/seed seedRequests, call matchTravelers(request, travelers) from @stellarcarry/core, and render the ranked results as premium cards -- the top match highlighted with a BorderBeam/glow, each showing travelerId, score (NumberTicker), route, and reputation; empty state when none qualify. Then replace the header "Connect wallet" placeholder with a REAL Freighter connect using @stellar/freighter-api (show a truncated address when connected; handle Freighter-not-installed gracefully). Add an e2e screenshot + interaction test for the match page. LOCAL network only. Gates: npm run build + npx playwright test.`,
    },
  },
  // Stage 6: escrow detail + lifecycle (premium)
  6: {
    title: 'UI: escrow detail + lifecycle actions (premium)',
    waves: [['a4']],
    tasks: {
      a4: `Add app/escrow/page.tsx: a premium escrow detail view with a visual STEPPER of the state (Created, Funded, Delivered, Released, with a Refunded branch) and action buttons (Fund, Confirm Delivery, Release, Refund) ENABLED ONLY in the valid state per the contract state machine (Release only from Delivered; Refund only from Funded; etc.). Wire each action to build the transaction via EscrowClient from @stellarcarry/core; if Freighter is connected sign+submit, else display the built XDR in a styled panel. Use the premium components and Stellar branding. Add an e2e screenshot + an interaction test asserting which buttons are enabled in each state. LOCAL only. Gates: npm run build + npx playwright test.`,
    },
  },
  // Stage 7: reputation, history + polish to premium
  7: {
    title: 'UI: reputation, history + polish to premium',
    waves: [['a4']],
    tasks: {
      a4: `Add app/reputation/page.tsx (a traveler reputation profile + completed-deliveries history, premium cards + NumberTicker) wired into the nav. Then do a POLISH PASS across EVERY screen guided by the visual review feedback: stronger hierarchy, motion, depth, gradients, consistent empty/loading/error states, responsive mobile+desktop, accessibility. Do not regress earlier screens or their tests. Every screen must have an up-to-date e2e screenshot. Push all screens toward a 10/10 premium look. Gates: npm run build + npx playwright test.`,
    },
  },
  // ════ "Departures" redesign — give the UI soul (designer-led) ════
  // Stage 8: the designer (a5) builds the design system FIRST; pages compose it after.
  8: {
    title: 'Departures design system (tokens + travel kit + brand)',
    waves: [['a5']],
    tasks: {
      a5: `Read apps/web/DESIGN.md IN FULL, then build the "Departures" design system (you own globals.css, components/brand/**, components/travel/**, app/_kit/page.tsx — do NOT edit page routes):
1. Design TOKENS in app/globals.css — the palette, type, and motion vars from DESIGN.md as Tailwind v4 @theme + CSS custom properties (space base with nebula glows, star-yellow, aurora teal/violet, ink). Pages will reference these; no raw hex anywhere.
2. The components/travel kit per the DESIGN.md contracts: BoardingPassCard, StarMapRoute (SVG star-field + animated flight-arc/comet), DepartureBoard (split-flap), PassportStamp + PassportPage, FlightArc, VaultSeal — each typed, with default/hover/loading/empty states, responsive, accessible, prefers-reduced-motion safe.
3. Brand in components/brand: logo (shooting-star whose tail is a flight-path arc) + wordmark, favicon, icon set (plane, globe, luggage, passport, vault, star).
4. app/_kit/page.tsx rendering every component in its states, with a Playwright screenshot in e2e/ (scroll before capture).
Gate: npm run build.`,
    },
  },
  // Stage 9: re-skin the core marketing/entry routes onto the kit.
  9: {
    title: 'Re-skin core (home, post, travelers) onto the kit',
    waves: [['a4']],
    tasks: {
      a4: `The "Departures" design system now exists (apps/web/DESIGN.md; tokens in globals.css; components/travel/* kit; components/brand/*). RE-SKIN these routes by COMPOSING the kit — no bespoke CSS, no raw hex, use the tokens + components:
- app/page.tsx — a "departures hall": a StarMapRoute hero with a live flight-arc, DepartureBoard stats, and the open requests as a wall of BoardingPassCards.
- app/post — "file a manifest": the request form styled as a boarding-pass / customs form (keep all validation + success state).
- app/travelers — travelers as BoardingPassCards (route, capacity, reputation) + add-traveler form + empty state.
Keep ALL existing functionality and tests green; update each e2e screenshot (scroll before capture for whileInView). Gate: npm run build + npx playwright test.`,
    },
  },
  // Stage 10: re-skin the transactional routes (the heart of the product).
  10: {
    title: 'Re-skin transactional (match, escrow, reputation) onto the kit',
    waves: [['a4']],
    tasks: {
      a4: `RE-SKIN the transactional routes by composing the "Departures" kit (apps/web/DESIGN.md) — no bespoke CSS / raw hex:
- app/match — ranked carriers as BoardingPassCards laid over a StarMapRoute of the request's route; keep matchTravelers from @stellarcarry/core and the Freighter connect.
- app/escrow — the VaultSeal as centerpiece (locks on Fund, breaks open on Release) plus a journey stepper (Created→Funded→Delivered→Released, Refunded branch); action buttons enabled ONLY in valid states per the contract; keep the EscrowClient transaction wiring.
- app/reputation — a PassportPage of delivery stamps + the reputation score (DepartureBoard/NumberTicker).
Keep functionality + tests green; update e2e screenshots. LOCAL only. Gate: npm run build + npx playwright test.`,
    },
  },
  // Stage 11: motion + polish. Designer refines shared motion first, then pages apply it.
  11: {
    title: 'Departures motion + final polish (every screen)',
    waves: [['a5'], ['a4']],
    tasks: {
      a5: `Polish the SHARED design system from the visual feedback (you own globals.css + components/travel + components/brand only — NOT page routes): wire the signature MOTION fully — flight-arc draw + travelling comet, star-field parallax + twinkle, DepartureBoard split-flap, PassportStamp thunk, VaultSeal lock/break — with solid prefers-reduced-motion fallbacks and responsive behavior. Gate: npm run build.`,
      a4: `FINAL polish pass across EVERY screen using the visual feedback: apply the kit's motion, strengthen hierarchy/depth, consistent empty/loading/error states, responsive mobile+desktop, accessibility. Do NOT regress earlier screens or their tests; every screen must have an up-to-date e2e screenshot. Gate: npm run build + npx playwright test.`,
    },
  },
};
const LAST_STAGE = Math.max(...Object.keys(STAGE_PLANS).map(Number));

// ===================== END CONFIG — machinery below =====================

function idsByRole(role: Role): string[] { return RUN_ORDER.filter((id) => AGENTS[id]?.role === role)
  .concat(Object.keys(AGENTS).filter((id) => AGENTS[id].role === role && !RUN_ORDER.includes(id))); }
function readPromptFile(name: string): string {
  const p = resolve(ROOT, 'agents', name);
  if (!existsSync(p)) throw new Error(`Agent prompt not found: ${p}`);
  return readFileSync(p, 'utf-8');
}
function readBlocked(): string { return existsSync(BLOCKED_FILE) ? readFileSync(BLOCKED_FILE, 'utf-8') : '(none)'; }

// ── Logging ──────────────────────────────────────────────────────────────
let LOG_STREAM: WriteStream | null = null;
function tsNow(): string { return new Date().toISOString().slice(11, 19); }
function initFileLogging(): string {
  const dir = resolve(ROOT, 'logs');
  try { mkdirSync(dir, { recursive: true }); } catch { /* ignore */ }
  const file = resolve(dir, `orchestrate-${new Date().toISOString().replace(/[:.]/g, '-')}.log`);
  LOG_STREAM = createWriteStream(file, { flags: 'a' });
  const tee = (orig: (...a: any[]) => void) => (...a: any[]) => { orig(...a); LOG_STREAM?.write(a.map(String).join(' ').replace(/\r/g, '') + '\n'); };
  console.log = tee(console.log.bind(console));
  console.error = tee(console.error.bind(console));
  return file;
}
function log(m = ''): void { if (m === '') console.log(); else console.log(`[${tsNow()}] ${m}`); }
function banner(t: string): void { log(); log('━'.repeat(64)); log(`  ${t}`); log('━'.repeat(64)); }

// ── DeepSeek guard ─────────────────────────────────────────────────────────
function assertDeepSeekEnv(): void {
  const base = process.env.ANTHROPIC_BASE_URL ?? '';
  banner('Orchestrator startup');
  log(`Workers:   ${ORCH_MODEL} (cheap: ${ORCH_MODEL_CHEAP})`);
  log(`Reasoning: ${ORCH_MODEL_REASON}  (planner + reviewers — tool-less)`);
  log(`Endpoint:  ${base || '(default Anthropic — NOT DeepSeek)'}`);
  if (!base.toLowerCase().includes('deepseek') && process.env.ALLOW_NON_DEEPSEEK !== '1') {
    log(); log('REFUSING TO RUN: ANTHROPIC_BASE_URL does not point at DeepSeek.');
    log('  export ANTHROPIC_BASE_URL=https://api.deepseek.com/anthropic'); log('  export ANTHROPIC_AUTH_TOKEN=$DEEPSEEK_API_KEY   (or ALLOW_NON_DEEPSEEK=1)');
    process.exit(1);
  }
}

// ── Gate machine ───────────────────────────────────────────────────────────
function execCapture(cmd: string, cwd: string, timeout = 180000): { ok: boolean; out: string } {
  try { return { ok: true, out: execSync(cmd, { cwd, encoding: 'utf-8', timeout, stdio: 'pipe' }) }; }
  catch (err: any) { return { ok: false, out: `${err.stdout ?? ''}${err.stderr ?? ''}${err.stdout || err.stderr ? '' : err.message ?? ''}` }; }
}
function runGateGroup(label: string, gates: GateCmd[]): string {
  const fails: string[] = [];
  for (const g of gates) {
    if (!existsSync(resolve(ROOT, g.presentIf))) { log(`  [Gate ${label}] skip — ${g.label}`); continue; }
    log(`  [Gate ${label}] ${g.label}...`);
    const { ok, out } = execCapture(g.cmd, resolve(ROOT, g.cwd));
    if (ok) log(`  [Gate ${label}] ok — ${g.label}`);
    else { log(`  [Gate ${label}] FAIL — ${g.label}`); fails.push(`### Gate failed: ${g.label}\nCommand: \`${g.cmd}\`\n\n\`\`\`\n${out.trim().slice(-4000)}\n\`\`\``); }
  }
  return fails.join('\n\n');
}
function runGates(workers: string[]): { passed: boolean; failures: Record<string, string> } {
  banner('Deterministic gates (build + tests)');
  const failures: Record<string, string> = {};
  for (const id of workers) {
    const gates = AGENTS[id].gates ?? [];
    if (!gates.length) { log(`  [Gate ${id}] none (non-code role)`); continue; }
    const f = runGateGroup(AGENTS[id].label, gates);
    if (f) failures[id] = f;
  }
  const passed = Object.keys(failures).length === 0;
  log(passed ? '  [Gates] ALL GREEN' : `  [Gates] FAIL: ${Object.keys(failures).join(', ')}`);
  return { passed, failures };
}

// ── Frozen spec tests ──────────────────────────────────────────────────────
function enforceFrozenTests(): string {
  const notes: string[] = [];
  for (const rel of FROZEN_TESTS) {
    if (!execCapture(`git cat-file -e HEAD:${rel}`, ROOT, 10000).ok) continue;
    const diff = execCapture(`git diff HEAD --name-only -- ${rel}`, ROOT, 10000);
    if (diff.ok && diff.out.trim()) {
      execCapture(`git checkout HEAD -- ${rel}`, ROOT, 10000);
      log(`  [Frozen] reverted edit to ${rel}`);
      notes.push(`- \`${rel}\` is a FROZEN spec test; your edit was reverted. Satisfy it — do NOT change the spec.`);
    }
  }
  return notes.length ? `\n\n## FROZEN SPEC VIOLATION\n${notes.join('\n')}` : '';
}

// ── Helpers for tool-less reasoning roles ──────────────────────────────────
// Reviewers can't call tools, so we hand them the diff as text. Planner can't
// write files, so it emits a "## Blocked" section and we persist it here.
function gitDiff(): string {
  // Mark untracked (newly created) files intent-to-add so they show up in the
  // diff — `git diff HEAD` alone omits new files, leaving reviewers blind to
  // every file the workers just created.
  execCapture('git add -A -N', ROOT, 10000);
  const out = execCapture('git --no-pager diff HEAD', ROOT, 30000).out.trim();
  execCapture('git reset -q', ROOT, 10000); // undo the intent-to-add markers
  return out ? out.slice(0, 20000) : '(no diff vs HEAD)';
}
function appendBlocked(stageNum: number, body: string): void {
  const prev = existsSync(BLOCKED_FILE) ? readFileSync(BLOCKED_FILE, 'utf-8') : '# Blocked items\n';
  writeFileSync(BLOCKED_FILE, `${prev}\n## Stage ${stageNum}\n${body.trim()}\n`);
  log(`  [Blocked] recorded under Stage ${stageNum} in BLOCKED.md`);
}
function extractBlocked(text: string): string | null {
  const m = text.match(/##+\s*Blocked[\s\S]*/i);
  if (!m) return null;
  const body = m[0].replace(/##+\s*Blocked[^\n]*\n?/i, '').trim();
  const clean = body.replace(/[*_()~`>\-\s]+/g, ' ').trim(); // strip md so "*(none …)*" reads as "none"
  return clean && !/^none\b/i.test(clean) ? body : null;
}

// ── Agent runner ───────────────────────────────────────────────────────────
// Every tool the claude-code SDK can expose. Reasoning roles (planner/reviewer)
// disallow ALL of them so they stay tool-less (see runAgent). If the SDK adds a
// tool and it's missing here, a reasoning role could pick it up and loop.
const ALL_TOOLS = [
  'Task', 'Bash', 'BashOutput', 'KillShell', 'KillBash', 'Glob', 'Grep',
  'Read', 'Edit', 'MultiEdit', 'Write', 'NotebookEdit', 'WebFetch', 'WebSearch',
  'TodoWrite', 'SlashCommand', 'ExitPlanMode', 'ListMcpResources', 'ReadMcpResource',
];
interface AgentResult { role: string; output: string; cost: number; duration: number }
interface RoundCost { round: number; phase: string; agents: AgentResult[] }
const SUMMARY_SUFFIX = `\n\nIMPORTANT: End with a "## Summary" heading: what you did, files changed, your verify results, and any issues.`;

async function runAgent(def: AgentDef, task: string): Promise<AgentResult> {
  const start = Date.now();
  const model = def.model ?? ORCH_MODEL;
  log(`[${def.label}] Starting (model ${model})`);
  log(`[${def.label}] Task: ${task.slice(0, 160).replace(/\s+/g, ' ').trim()}${task.length > 160 ? '…' : ''}`);
  let cost = 0, turns = 0, aborted = false; const texts: string[] = [];
  // Wall-clock backstop: abort a genuinely hung agent (never a turn cap — see config).
  const budgetMs = def.role === 'worker' ? WORKER_WALL_MS : REASON_WALL_MS;
  const controller = new AbortController();
  const timer = setTimeout(() => {
    aborted = true;
    log(`[${def.label}] ABORTED — wall-clock budget (${Math.round(budgetMs / 60_000)}m) exceeded; using partial output`);
    controller.abort();
  }, budgetMs);
  try {
  for await (const message of query({
    prompt: task + SUMMARY_SUFFIX,
    options: {
      cwd: ROOT,
      abortController: controller,
      appendSystemPrompt: readPromptFile(def.systemFile), // NOT `systemPrompt` (silently ignored)
      model, maxTurns: def.role === 'worker' ? 100 : 8,
      // Reasoning models (R1) can't reliably tool-call. Planner + reviewers run
      // TOOL-LESS: the orchestrator inlines all context (diff, prior results) as
      // text and applies side-effects (BLOCKED.md) deterministically. Workers get
      // the full toolset. NOTE: allowedTools:[] does NOT disable tools in this SDK
      // (empty = unrestricted), so we MUST name EVERY tool in disallowedTools for
      // reasoning roles — an incomplete list lets the model loop (e.g. a planner that
      // keeps every un-listed tool will spawn Tasks / poll BashOutput / edit files
      // for hundreds of turns). Keep ALL_TOOLS in sync with the SDK's tool surface.
      allowedTools: def.role === 'worker' ? ['Read', 'Write', 'Edit', 'Bash', 'Glob', 'Grep'] : [],
      disallowedTools: def.role === 'worker' ? [] : ALL_TOOLS,
    },
  })) {
    if (message.type === 'assistant') {
      turns++;
      const elapsed = ((Date.now() - start) / 1000).toFixed(0);
      const t = message.message.content.filter((b: any) => b.type === 'text').map((b: any) => b.text);
      const tools = message.message.content.filter((b: any) => b.type === 'tool_use').map((b: any) => b.name);
      if (tools.length) log(`[${def.label}] turn ${turns} | ${elapsed}s | tools: ${tools.join(', ')}`);
      else if (t.length) log(`[${def.label}] turn ${turns} | ${elapsed}s | ${t[0].slice(0, 100).replace(/\s+/g, ' ').trim()}…`);
      if (t.length) texts.push(...t);
    } else if (message.type === 'result') { cost = (message as any).total_cost_usd ?? 0; }
  }
  } catch (err: any) {
    // An abort surfaces here as a thrown error — swallow it (we keep partial output);
    // re-throw anything that is NOT our intentional budget abort.
    if (!aborted) throw err;
  } finally { clearTimeout(timer); }
  const out = (def.role === 'reviewer' ? pickReview(texts) : pickSummary(texts)) || '(no text output)';
  const duration = (Date.now() - start) / 1000;
  log(`[${def.label}] Done in ${duration.toFixed(0)}s | ${turns} turns | $${cost.toFixed(4)}${aborted ? ' | ABORTED (budget)' : ''}`);
  return { role: def.label, output: out, cost, duration };
}
function pickReview(t: string[]): string { for (let i = t.length - 1; i >= 0; i--) if (/## Review Result/i.test(t[i])) return t[i]; const j = t.join('\n\n'); return /## Review Result/i.test(j) ? j : (t[t.length - 1] ?? ''); }
function pickSummary(t: string[]): string { for (let i = t.length - 1; i >= 0; i--) { const m = t[i].match(/## Summary[\s\S]*/i); if (m) return m[0]; } return t[t.length - 1] ?? ''; }

// ── Phase: PLAN ────────────────────────────────────────────────────────────
async function runPlanners(stageNum: number, plan: StagePlan, priorSummary: string, skip: Set<string>): Promise<string> {
  const planners = idsByRole('planner').filter((id) => !skip.has(id));
  if (!planners.length) return '';
  banner(`Stage ${stageNum} — PLAN`);
  let context = '';
  for (const id of planners) {
    const task = `Plan stage ${stageNum} ("${plan.title}").

## Previous stage outcome
${priorSummary || '(none)'}

## Currently blocked items (BLOCKED.md)
${readBlocked()}

## Base tasks for the workers this stage
${JSON.stringify(plan.tasks, null, 2)}

Produce concrete, codeable guidance for the workers. If a base task is NOT codeable as-is
(missing decision, external dependency, infeasible), propose a codeable alternative, OR list it under a
"## Blocked" section at the END of your reply with a clear reason (the orchestrator records it for the morning).
End with a "## Plan" section the workers will read.`;
    const r = await runAgent(AGENTS[id], task);
    const blocked = extractBlocked(r.output);
    if (blocked) appendBlocked(stageNum, `From ${AGENTS[id].label}:\n${blocked}`);
    context += `\n\n## Plan from ${AGENTS[id].label}\n${r.output}`;
  }
  return context.slice(0, 4000);
}

// ── Phase: REVIEW (N critics, merged) ──────────────────────────────────────
async function runReviewers(workers: string[], results: Record<string, AgentResult>, skip: Set<string>, scope: string, visualReport = ''): Promise<{ approved: boolean; changes: Record<string, string> }> {
  const reviewers = idsByRole('reviewer').filter((id) => !skip.has(id));
  if (!reviewers.length) return { approved: true, changes: {} };
  const reports = workers.map((id) => `## ${AGENTS[id].label} Report\n\n${results[id]?.output ?? '(none)'}`).join('\n\n');
  const headings = workers.map((id) => `"### Required Changes for ${AGENTS[id].reviewHeading}"`).join(', ');
  const diff = gitDiff(); // inlined so tool-less reasoning reviewers can see the code
  // The design reviewer also acts as the JUDGE OF qwen: it reads qwen's raw visual
  // observations and keeps only the real, theme-specific misses (a4) as changes.
  const judgeId = reviewers.includes('review_design') ? 'review_design' : reviewers[reviewers.length - 1];
  const merged: Record<string, string> = {}; let approvedAll = true;
  for (const rid of reviewers) {
    const def = AGENTS[rid];
    const lens = def.perspective ? `\n\nReview specifically through this lens: ${def.perspective}.` : '';
    const visualBlock = (visualReport && rid === judgeId && workers.includes('a4'))
      ? `\n\n## Visual observations from a LOCAL VISION MODEL (qwen) — YOU ARE THE JUDGE\nqwen can see the screenshots but is MISCALIBRATED: it clusters scores at 7-8 and repeats generic advice. Treat its text as raw observations ONLY. Using the art-direction brief and the diff, put into "### Required Changes for A4" ONLY concrete, theme-specific, real visual misses (wrong palette, a signature component/motion that's missing, broken hierarchy). DISCARD vague boilerplate like "add subtle animations". If qwen surfaced nothing real, do NOT request A4 changes for visuals.\n${visualReport}`
      : '';
    const prompt = `Gates already passed build+tests — focus on what a gate cannot judge.${lens}\n\n## THIS STAGE'S SCOPE\nOnly REQUEST_CHANGES for issues WITHIN these deliverables. Anything belonging to a LATER stage (e.g. a function deliberately left as a stub this stage, or a command not yet due) goes in non-blocking "### Notes" — NOT in Required Changes:\n${scope}\n\n${reports}\n\n## Diff under review\n\`\`\`diff\n${diff}\n\`\`\`${visualBlock}\n\nUse the EXACT output format, splitting changes into ${headings}.`;
    let verdict: { approved: boolean; changes: Record<string, string> } | null = null; let raw = '';
    for (let attempt = 0; attempt < 3 && !verdict; attempt++) {
      const r = await runAgent(def, prompt);
      raw = r.output;
      if (/## Review Result:\s*(APPROVE|REQUEST_CHANGES)/i.test(r.output)) verdict = parseVerdict(r.output, workers);
      else log(`  [${def.label}] unparseable — retry ${attempt + 1}/3`);
    }
    log(`  ── ${def.label} full verdict ──\n${raw}\n  ── end verdict ──`);
    if (!verdict) { log(`  [${def.label}] unparseable — treating as REQUEST_CHANGES`); verdict = { approved: false, changes: {} }; }
    if (!verdict.approved) approvedAll = false;
    for (const [wid, txt] of Object.entries(verdict.changes)) merged[wid] = [merged[wid], `From ${def.label}:\n${txt}`].filter(Boolean).join('\n\n');
  }
  return { approved: approvedAll, changes: merged };
}
function parseVerdict(out: string, workers: string[]): { approved: boolean; changes: Record<string, string> } {
  const approved = /Review Result:\s*APPROVE/i.test(out) && !/REQUEST[_\s]?CHANGES/i.test(out);
  const changes: Record<string, string> = {};
  if (!approved) for (const id of workers) {
    const h = (AGENTS[id].reviewHeading ?? id).replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    const m = out.match(new RegExp(`#{2,4}\\s*Required Changes for ${h}[\\s\\S]*?(?=#{2,4}\\s*Required Changes for |#{2,4}\\s*Notes|$)`, 'i'));
    if (m && m[0].trim().length > 30 && !/\bNone\b/i.test(m[0])) changes[id] = m[0].trim();
  }
  return { approved, changes };
}

// ── Phase: blocked triage (planner decides) ────────────────────────────────
async function plannerTriage(stageNum: number, failures: Record<string, string>, skip: Set<string>): Promise<void> {
  const planners = idsByRole('planner').filter((id) => !skip.has(id));
  const summary = Object.entries(failures).map(([id, f]) => `### ${AGENTS[id].label}\n${f.slice(0, 1500)}`).join('\n\n');
  if (!planners.length) { appendBlocked(stageNum, `Auto-blocked (no planner):\n${summary}`); return; }
  banner(`Stage ${stageNum} — BLOCKED TRIAGE (planner decides)`);
  const r = await runAgent(AGENTS[planners[0]], `Stage ${stageNum} still has RED gates after the max rounds:\n\n${summary}\n\nFor each failure, DECIDE: (a) propose a concrete alternative approach the workers can try in a later stage, or (b) mark it BLOCKED for a human with a clear reason. List your decisions under a "## Blocked" section; the orchestrator records them, then continues to the next stage.`);
  appendBlocked(stageNum, `Planner triage:\n${extractBlocked(r.output) ?? r.output.slice(0, 1500)}`);
}

function fixPrompt(task: string, feedback: string): string {
  return `Gates and/or reviewers found issues. Fix ONLY what is listed; stay in your ownership.\n\n## Original task\n${task}\n\n## Required changes\n${feedback}\n\nVerify (your gates green) before writing your ## Summary.`;
}

// ── Run a single stage ─────────────────────────────────────────────────────
interface StageOptions { skipReview: boolean; skip: Set<string>; maxRounds: number; reviewOnly: boolean }
function activeWorkers(plan: StagePlan, skip: Set<string>): string[] {
  const ids = new Set<string>();
  for (const wave of plan.waves) for (const id of wave) if (plan.tasks[id] && !skip.has(id)) ids.add(id);
  return RUN_ORDER.filter((id) => ids.has(id));
}

// Local visual review (qwen via Ollama) — "the EYE", not the judge. It reports raw
// observations of each screenshot against the art-direction brief plus a soft score.
// qwen is miscalibrated (clusters 7-8, generic notes), so this is NOT fed to A4
// directly: the R1 design reviewer judges it (keeps real misses, drops boilerplate).
// The scores are used only for plateau detection.
async function ollamaUp(): Promise<boolean> {
  try { const r = await fetch('http://localhost:11434/api/version'); return r.ok; } catch { return false; }
}
async function visualReviewWeb(): Promise<{ report: string; scores: Record<string, number> } | null> {
  if (!(await ollamaUp())) { log('  [Visual] Ollama unavailable — skipping visual review'); return null; }
  const { report, scores } = await evalDir(resolve(ROOT, 'apps/web/screenshots'));
  log(`\n  ── Visual observations (qwen — the eye) ──\n${report}\n  ── end ──`);
  return { report, scores };
}
// Plateau: true when no screen improved vs the previous round (qwen's ceiling reached).
function visualPlateaued(prev: Record<string, number>, cur: Record<string, number>): boolean {
  const screens = Object.keys(cur);
  if (!screens.length || !Object.keys(prev).length) return false;
  return screens.every((s) => (cur[s] ?? 0) <= (prev[s] ?? 0));
}

async function runStage(stageNum: number, opts: StageOptions, priorSummary = ''): Promise<{ costs: RoundCost[]; success: boolean; summary: string }> {
  const plan = STAGE_PLANS[stageNum];
  if (!plan) throw new Error(`No plan for stage ${stageNum}`);
  banner(`STAGE ${stageNum} — ${plan.title} (max ${opts.maxRounds} rounds)`);
  const workers = activeWorkers(plan, opts.skip);
  const results: Record<string, AgentResult> = {};
  const costs: RoundCost[] = [];
  // What THIS stage owns — reviewers block only on issues within this scope.
  const reviewScope = workers.map((id) => `### ${AGENTS[id].label}\n${plan.tasks[id] ?? '(no task this stage)'}`).join('\n\n');

  // Review-only: gate + review the code already on disk. No planner, no dev,
  // no fix loop, no commit, no reset — fast way to audit the review behavior.
  if (opts.reviewOnly) {
    banner(`STAGE ${stageNum} — REVIEW-ONLY (current working tree)`);
    enforceFrozenTests();
    const gate = runGates(workers);
    const rev = await runReviewers(workers, results, opts.skip, reviewScope);
    log(`\n  >>> REVIEW-ONLY — gates ${gate.passed ? 'GREEN' : 'RED'}, reviewers ${rev.approved ? 'APPROVE' : 'REQUEST_CHANGES'} <<<`);
    return { costs, success: gate.passed && rev.approved, summary: '' };
  }

  // PLAN
  const planContext = opts.skip.has('planner') ? '' : await runPlanners(stageNum, plan, priorSummary, opts.skip);

  // DEV (waves)
  banner(`Stage ${stageNum} — DEV`);
  for (const wave of plan.waves) {
    const ids = wave.filter((id) => workers.includes(id));
    if (!ids.length) continue;
    log(`\n  Wave: ${ids.join(', ')}`);
    const done = await Promise.all(ids.map((id) => runAgent(AGENTS[id], plan.tasks[id] + (planContext ? `\n\n# Plan context for this stage\n${planContext}` : ''))));
    ids.forEach((id, i) => { results[id] = done[i]; });
    if (BUILD_BETWEEN_WAVES) execCapture(BUILD_BETWEEN_WAVES, ROOT);
  }
  costs.push({ round: 1, phase: 'dev', agents: workers.map((id) => results[id]) });

  // GATE + REVIEW loop
  let frozenNote = enforceFrozenTests();
  let gate = runGates(workers);
  let approved = opts.skipReview;

  let lastScores: Record<string, number> = {};
  for (let round = 1; round <= opts.maxRounds; round++) {
    // qwen (the EYE) runs first when web is in play; its raw observations are handed
    // to the design reviewer (the JUDGE) — advisory, never a gate. Capped to the first
    // 2 rounds and dropped on plateau so it can't burn rounds it cannot verify.
    let visualReport = '';
    if (workers.includes('a4') && !opts.skipReview) {
      const vis = await visualReviewWeb();
      if (vis) {
        if (round > 2) log('  [Visual] past round 2 — qwen no longer drives fixes (cap)');
        else if (visualPlateaued(lastScores, vis.scores)) log('  [Visual] plateau — qwen scores not improving; not driving further fixes');
        else visualReport = vis.report;
        lastScores = vis.scores;
      }
    }
    let reviewChanges: Record<string, string> = {};
    if (!opts.skipReview) {
      const v = await runReviewers(workers, results, opts.skip, reviewScope, visualReport);
      approved = v.approved; reviewChanges = v.changes;
    }
    const fixes: Record<string, string> = {};
    for (const id of workers) {
      const codeRole = (AGENTS[id].gates ?? []).length > 0;
      const parts = [gate.failures[id], reviewChanges[id], codeRole ? frozenNote : ''].filter(Boolean);
      if (parts.length) fixes[id] = parts.join('\n\n');
    }
    if (gate.passed && Object.keys(fixes).length === 0) {
      log(`\n  >>> STAGE ${stageNum} COMPLETE — gates green${opts.skipReview ? '' : approved ? ', reviewers approved' : ''} <<<`);
      break;
    }
    if (round === opts.maxRounds) { log(`\n  >>> Max ${opts.maxRounds} rounds — gates ${gate.passed ? 'GREEN' : 'RED'} <<<`); break; }

    banner(`Stage ${stageNum} — FIX round ${round + 1} (${Object.keys(fixes).join(', ') || 'none'})`);
    for (const id of RUN_ORDER) {
      if (!fixes[id]) continue;
      log(`  ── ${AGENTS[id].label} must fix ──\n${fixes[id]}\n  ── end ──`);
      results[id] = await runAgent(AGENTS[id], fixPrompt(plan.tasks[id], fixes[id]));
      if (BUILD_BETWEEN_WAVES) execCapture(BUILD_BETWEEN_WAVES, ROOT);
    }
    costs.push({ round: round + 1, phase: 'fix', agents: workers.map((id) => results[id]) });
    frozenNote = enforceFrozenTests();
    gate = runGates(workers);
  }

  // On unresolved RED: planner decides (replan / mark for morning), then we continue.
  if (!gate.passed) await plannerTriage(stageNum, gate.failures, opts.skip);

  const success = gate.passed;
  commitStageWork(stageNum, success);
  const summary = workers.map((id) => `${AGENTS[id].label}: ${results[id]?.output?.slice(0, 600) ?? ''}`).join('\n\n');
  return { costs, success, summary };
}

// ── Git ────────────────────────────────────────────────────────────────────
function commitStageWork(stageNum: number, success: boolean): void {
  const title = STAGE_PLANS[stageNum]?.title ?? '';
  const msg = success ? `feat(stage-${stageNum}): ${title}` : `wip(stage-${stageNum}): [GATES FAILED] ${title}`;
  try {
    if (!execSync('git status --porcelain', { cwd: ROOT, encoding: 'utf-8' }).trim()) { log('  No changes to commit.'); return; }
    execSync('git add -A', { cwd: ROOT });
    execSync(`git commit -m ${JSON.stringify(msg)}`, { cwd: ROOT });
    log(`  Committed: ${execSync('git rev-parse --short HEAD', { cwd: ROOT, encoding: 'utf-8' }).trim()} — ${msg}`);
  } catch (err: any) { log(`  Commit failed: ${err.message}`); }
}

// ── Main ───────────────────────────────────────────────────────────────────
async function main() {
  const args = process.argv.slice(2);
  const valOf = (n: string) => { const i = args.indexOf(n); return i !== -1 ? args[i + 1] : undefined; };
  const opts: StageOptions = {
    skipReview: args.includes('--skip-review'),
    skip: new Set((valOf('--skip') ?? '').split(',').map((s) => s.trim()).filter(Boolean)),
    maxRounds: valOf('--max-rounds') ? parseInt(valOf('--max-rounds')!, 10) : DEFAULT_MAX_ROUNDS,
    reviewOnly: args.includes('--review-only'),
  };
  const continuous = args.includes('--continuous');
  const stageArg = valOf('--stage');
  const stageNum = stageArg !== undefined ? parseInt(stageArg, 10) : undefined;
  const startStage = valOf('--start-stage') ? parseInt(valOf('--start-stage')!, 10) : 0;

  const willRun = continuous || (stageNum !== undefined && Boolean(STAGE_PLANS[stageNum]));
  if (!willRun) {
    console.log(`Usage:
  npx tsx orchestrate.ts --stage <n>                    Run one stage
  npx tsx orchestrate.ts --stage <n> --skip a2,planner  Skip agents
  npx tsx orchestrate.ts --stage <n> --skip-review      Gates only
  npx tsx orchestrate.ts --stage <n> --review-only      Gate + review the code on disk (no dev/fix/commit)
  npx tsx orchestrate.ts --continuous                   All stages, unattended
  npx tsx orchestrate.ts --continuous --start-stage <n> Resume from a stage`);
    process.exit(1);
  }
  const logFile = initFileLogging();
  assertDeepSeekEnv();
  log(`Full log: ${logFile}`);

  if (continuous) {
    let prior = '';
    for (let s = startStage; s <= LAST_STAGE; s++) {
      if (!STAGE_PLANS[s]) continue;
      try {
        const { success, summary } = await runStage(s, opts, prior);
        prior = summary;
        if (!success) log(`\n  Stage ${s} had blocked items — planner triaged; continuing to next stage.`);
      } catch (err: any) { log(`\n  !!! Stage ${s} threw: ${err.message} — stopping.`); break; }
    }
    return;
  }
  await runStage(stageNum!, opts);
}

main().catch((err) => { console.error('Orchestrator failed:', err); process.exit(1); });
